### GET ALL ITEMS
GET http://localhost:8080/items HTTP/1.1


### GET AN ITEM
GET http://localhost:8080/items/1 HTTP/1.1


### POST AN ITEM
GET http://localhost:8080/items HTTP/1.1


### UPDATE AN ITEM
GET http://localhost:8080/items/1 HTTP/1.1


### DELETE AN ITEM
GET http://localhost:8080/items/1 HTTP/1.1